### ISSUE TITLE
blog post for Postgres query with GO

### ISSUE THREAD

**Issue by ShiftRL** [codefordenver/shift-api#13]

**Comment by ShiftRL** [comment]
https://flaviocopes.com/golang-tutorial-rest-api/

**Comment by ShiftRL** [comment]
https://astaxie.gitbooks.io/build-web-application-with-golang/en/05.4.html

**Comment by tfielder** [comment]
Added to wiki page -tf 02.25.19 https://github.com/codefordenver/shift-api/wiki
