### ISSUE TITLE
swagger integration with AWS api gateway + Lambda

### ISSUE THREAD

**Issue by ZhuNikki** [codefordenver/shift-api#6]
https://swagger.io/blog/api-development/swagger-amazon-api-gateway-and-lambda/
swagger post, include video

**Comment by ZhuNikki** [comment]
https://cloudonaut.io/create-a-serverless-restful-api-with-api-gateway-swagger-lambda-and-dynamodb/ There is an article about building API with Api Gateway + Swagger +
Lambda

**Comment by ZhuNikki** [comment]
https://medium.com/dailyjs/how-to-build-a-node-js-api-using-postgres-lambda-and-api-gateway-3211a4570cea

**Comment by ZhuNikki** [comment]
https://apievangelist.com/2017/11/06/a-simple-api-using-aws-rds-lambda-and-api-gateway/

**Comment by tfielder** [comment]
Added to wiki page -tf 02.25.19 https://github.com/codefordenver/shift-api/wiki
